baseurl = "https://davidblitz.github.io/"
title = "BlitzBlog"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "davidblitz"
disqusShortname = ""
googleAnalytics = ""

[Author]
    name = "David Blitz"
    profile = "https://github.com/davidblitz"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "BlitzBlog"
    description = "The Eternal Spot on Your Mind"
    github = "https://github.com/davidblitz"
    opengraph = true

[Permalinks]
    post = "/:year/:month/:day/:filename/"
